from functions import read_list_from_file

search_youtube=read_list_from_file('command\\пошук_ютуб.txt')
znach=read_list_from_file('command\\чат_gpt.txt')
search_google=read_list_from_file('command\\пошук_гугл.txt')
scr_video=read_list_from_file('command\\запис_екрану.txt')
micro_0=read_list_from_file("command\\мікрофон.txt")
res_wkl_0=read_list_from_file("command\\пов_закр_вкладок.txt")
close_wkl_0=read_list_from_file("command\\закрити_вкладку.txt")
open_wkl_0=read_list_from_file("command\\нові_вкладки.txt")
close_0=read_list_from_file("command\\закрити_пот_програму.txt")
zverni_0=read_list_from_file("command\\звренення_програми.txt")
valume_on_off_0=read_list_from_file("command\\вкл_викл_звуку.txt")
screenshot=read_list_from_file("command\\знімок_екрану.txt")
comp_slowar=read_list_from_file("command\\зпуск_програм.txt")
command_slowar=read_list_from_file("command\\список_команд.txt")
up=read_list_from_file('command\\вижче.txt')
down=read_list_from_file('command\\нижче.txt')